sudo: false
language: c
compiler: gcc

addons:
  apt:
    packages:
      - gfortran

install:
  - export PATH=$HOME/miniconda/bin:$PATH
  - make install-conda

script:
  - make build-sundials
  - make install-sundials

notifications:
  email:
    on_failure: always
