sudo: false
language: c
compiler: gcc

install:
  - export PATH=$HOME/miniconda/bin:$PATH
  - echo $PATH
  - make install-conda

script:
  - make build-sundials
  - make install-sundials

notifications:
  email:
    on_failure: always
